### ISSUE TITLE
Issue: Optimize CI/CD Pipeline for Bookshop & Bookshop-Admin

### ISSUE THREAD

**Issue by Rurutia1027** [Rurutia1027/Spring-Dubbo-Distributed-REST-Service#30]
## Description:

The Bookshop-Admin build depends on the JAR from Bookshop. The pipeline should ensure:
- Bookshop builds first and installs the JAR in .m2/repository.
- Bookshop-Admin waits for the JAR before starting.
- Common setup steps (JDK, Maven cache) are shared to avoid duplication.

## Tasks:
- Ensure Bookshop runs first and installs dependencies.
- Use needs: bookshop-build to make Bookshop-Admin wait.
- Extract common setup steps to reduce redundancy.

## Goal:

Faster, more efficient CI/CD with correct build order and no redundant steps. 🚀

## `workflow.yml` to be verify 
```yml
name: CI/CD Pipeline - BookShop & Admin

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

  bookshop-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Bookshop Project
        run: cd bookshop && mvn clean install -DskipTests

      - name: Run Tests with JaCoCo
        run: cd bookshop && mvn test jacoco:report

      - name: Upload Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key java --value-file bookshop/target/site/jacoco/jacoco.xml

  bookshop-admin-build:
    runs-on: ubuntu-latest
    needs: bookshop-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Bookshop-Admin Project
        run: cd bookshop-admin && mvn clean package -DskipTests

      - name: Run Tests with JaCoCo
        run: cd bookshop-admin && mvn test jacoco:report

      - name: Upload Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key java --value-file bookshop-admin/target/site/jacoco/jacoco.xml
```
